{"name": "testcase2", "status": "broken", "statusDetails": {"message": "IndexError: tuple index out of range", "trace": "a = (<pytestloc.test_case.test_login_3.TestLoginCheck object at 0x000002A7D33BF630>,), kw = {}, __tracebackhide__ = True\nparams = OrderedDict(), args = ['<pytestloc.test_case.test_login_3.TestLoginCheck object at 0x000002A7D33BF630>']\n\n    @wraps(func)\n    def impl(*a, **kw):\n        __tracebackhide__ = True\n        params = func_parameters(func, *a, **kw)\n        args = list(map(lambda x: represent(x), a))\n>       with StepContext(self.title.format(*args, **params), params):\nE       IndexError: tuple index out of range\n\nf:\\python36\\lib\\site-packages\\allure_commons\\_allure.py:140: IndexError"}, "attachments": [{"name": "log", "source": "60f62b8b-e59b-4067-8590-b8c393c87aff-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "9dc84f6d-b957-45f2-be4a-bf970dd4403a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "d1b8b30f-1f90-4762-a37e-ecea0706ed52-attachment.txt", "type": "text/plain"}], "start": 1553406785619, "stop": 1553406785619, "uuid": "c86c1fb1-ac57-4bc4-b90f-f5a0190458de", "historyId": "1abff4cbd64c763b65d6762394c559a0", "fullName": "test_login_3.TestLoginCheck#testcase2", "labels": [{"name": "story", "value": "成功登录"}, {"name": "feature", "value": "测试登录"}, {"name": "severity", "value": "blocker"}, {"name": "suite", "value": "test_login_3"}, {"name": "subSuite", "value": "TestLoginCheck"}, {"name": "host", "value": "winholepc"}, {"name": "thread", "value": "15764-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_3"}]}